name: Simple Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: demo
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      working-directory: docker-hello-world/infrastructure
      run: terraform init

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      working-directory: docker-hello-world/infrastructure
      run: |
        terraform apply -auto-approve -var-file="terraform-simple.tfvars"
        echo "🌐 Application URL:"
        terraform output application_url

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      working-directory: docker-hello-world/infrastructure
      run: terraform destroy -auto-approve -var-file="terraform-simple.tfvars"