version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: guestbook_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: simple_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DB_HOST: postgres
      DB_NAME: guestbook_db
      DB_USER: app_user
      DB_PASSWORD: simple_password
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data: