name: Test AWS Credentials

on:
  workflow_dispatch:

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test AWS CLI
      run: |
        echo "Testing AWS credentials..."
        aws sts get-caller-identity
        echo "✅ AWS credentials are working!"

    - name: Check permissions
      run: |
        echo "Testing basic AWS permissions..."
        aws ec2 describe-regions --region us-east-1
        echo "✅ EC2 permissions working!"